=== lenik/jazz/xml/current/xmod/modpdb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:pdb="http://www.bodz.net/xml/current/xmod/modpdb" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bodz.net/xml/current/xmod/modpdb" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="modpdb">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pdb:docobj">
					<xs:sequence>
						<xs:element name="import" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="href" type="xs:string" use="required"/>
								<xs:attribute name="type" type="xs:string">
									<xs:annotation>
										<xs:documentation>reserved</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="pdb:table"/>
							<xs:element ref="pdb:view"/>
							<xs:element name="hr" type="pdb:docobj">
								<xs:annotation>
									<xs:documentation>used to generate beautiful documents.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:choice>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
		<xs:unique name="u_table_view">
			<xs:selector xpath="pdb:table | pdb:view"/>
			<xs:field xpath="@name"/>
		</xs:unique>
	</xs:element>
	<xs:element name="table">
		<xs:annotation>
			<xs:documentation>REQ: @name

opts: 
    c=abstract
    D=cache/dict
    Dr=redundant (info-dict)
    Ro=read-only table
    S=sub-table
        Sc=Columns-Continue (1:1)
        S, Ss=Sub-Table (1:n)
        Sr=Relationships (n:m)
        Sx=eXtensible-Fields (1:n:n)
    T=transient table
</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pdb:docobj">
					<xs:sequence>
						<xs:element name="field" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>REQ: @name

opts: 
    N=nullable
    K=primary key (group)
    F([nam,] n:m ? table.field[, disp-sql]) = foreign key
        F-> normal ref-integrity
        F--> no ref-integrity
        F=> cascade-update
        F>> cascade-delete
    I(nam)=index (group)
    Ic(nam)=clustered index
    U(nam)=unique (group)
    T(field, ?)=timestamp
    V(field, ?)=version
    S?=special mode
        Sd=cache/display-name
    D(value)=default value
    Dx(sql-exp)=default exp
    Di(gen-method) = identity
</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="pdb:docobj">
										<xs:attribute name="type" type="xs:string">
											<xs:annotation>
												<xs:documentation>sql type (YaSQL)
default C[,32]

B[min,max] = binary
Bt = bit/boolean
C[min,max] = 
    char/varchar/text
Cn[min,max] = 
    nchar/nvarchar/ntext
T? = datetime
    Td=date
    Tt=time
    Ts=timestamp
F?=float (default sys/float)
I?=integer (default sys/int)
    I8, I16, I32, I64, etc.
M[totlen,declen] = money
N[totlen,declen] = number</xs:documentation>
											</xs:annotation>
										</xs:attribute>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="index" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>(deprecated)</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="pdb:docobj">
										<xs:sequence>
											<xs:element name="field" type="xs:string" maxOccurs="unbounded"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="check" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="pdb:docobj">
										<xs:sequence>
											<xs:element name="src" type="pdb:yasql"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="trigger" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="pdb:docobj">
										<xs:sequence>
											<xs:element name="src" type="pdb:yasql"/>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="row" minOccurs="0" maxOccurs="unbounded">
							<xs:annotation>
								<xs:documentation>data row</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>field data</xs:documentation>
										</xs:annotation>
									</xs:any>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="base" type="xs:string">
						<xs:annotation>
							<xs:documentation>extends the specified table, 

no duplicated fields is allowed.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
		<xs:unique name="u_field">
			<xs:selector xpath="field"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="u_index">
			<xs:selector xpath="index"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="u_check">
			<xs:selector xpath="check"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="u_trigger">
			<xs:selector xpath="trigger"/>
			<xs:field xpath="@name"/>
		</xs:unique>
	</xs:element>
	<xs:element name="view">
		<xs:annotation>
			<xs:documentation>REQ: @name

opts: 
    D=cache/dict</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="pdb:docobj">
					<xs:sequence>
						<xs:element name="src" type="pdb:yasql"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="docobj">
		<xs:sequence>
			<xs:element ref="pdb:xdoc" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id">
			<xs:annotation>
				<xs:documentation>xml id, used in $varname interpolation</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>object name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="qname" type="xs:string">
			<xs:annotation>
				<xs:documentation>qualified name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="opts" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>options, in components' local-syntax

Common Options: 
    c=comment-out
    </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="cat" type="xs:string">
			<xs:annotation>
				<xs:documentation>category for organization purpose.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="disp" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>display string</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="icon" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>display icon</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="info" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>short help-info</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="xdoc">
		<xs:annotation>
			<xs:documentation>built-in doc</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="html" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="yasql">
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== lenik/jazz/xml/current/xmod/instances/commons.pdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<modpdb xmlns="http://www.bodz.net/xml/current/xmod/modpdb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bodz.net/xml/current/xmod/modpdb
C:\.radiko\.miaj\mirror\site\xml\current\xmod\modpdb.xsd" name="MisCommons" qname="net.bodz.mis.commons" cat="net.bodz.mis" disp="Mis.Commons">
	<import href="base.pdb.xml"/>
	<!--User System-->
	<table name="_Perm" opts="c" disp="General Permission">
		<field name="perm" disp="Permission Key" type="I" opts="K"/>
		<field name="dpl" disp="Declared Privilege Level" type="I" opts="D(0)" info="Values ::=
-1 = Forbidden
0  = Inherit
1+ = Level"/>
		<field name="cpl" disp="Current Privilege Level" type="I" opts="N" info="Values ::=
0- = Forbidden
1+ = Level"/>
		<field name="cxt" disp="CPL Expiration Time" type="Ts" opts="NI" info="set cpl to null after timeout"/>
	</table>
	<table name="_Ext" opts="c" disp="Customizable Extension">
		<field name="key" disp="Ext Key" type="C[,30]" opts="K"/>
		<field name="ival" disp="Ext Value / Integer" type="I" opts="D(0)"/>
		<field name="cval" disp="Ext Value / String" type="C[,120]" opts="D('')"/>
	</table>
	<table name="CUser" base="after(_Docobj)" disp="Common User">
		<field name="id" disp="id/usr" type="I" opts="KDi"/>
	</table>
	<table name="CGroup" base="after(_Docobj)" disp="Common Group, also User-Type">
		<field name="id" disp="id/grp" type="I" opts="KDi"/>
		<field name="creator" disp="User created the group" type="NI" opts="KF(n:1 => User.id)"/>
	</table>
	<table name="CRole" base="after(_Docobj)" disp="Common Role">
		<field name="id" disp="id/rol" type="I" opts="KDi"/>
		<field name="creator" disp="User created the role" type="NI" opts="KF(n:1 => User.id)"/>
		<field name="t" disp="Role Type" type="C" opts="D('G')" info="Values ::=
'G' = General-Role
'M' = Member-Role"/>
	</table>
	<table name="CPerm" base="after(_Docobj)" disp="Common Permission">
		<field name="id" disp="id/perm" type="I" opts="KDi"/>
		<field name="creator" disp="User created the role" type="NI" opts="KF(n:1 => User.id)"/>
	</table>
	<table name="CUserPerm" opts="S" base="after(_Perm)" disp="Common User Permission">
		<field name="usr" disp="Owner User" type="I" opts="KF(n:1 => User.id)"/>
	</table>
	<table name="CGroupPerm" opts="S" base="after(_Perm)" disp="Common Group Customizable Extension">
		<field name="grp" disp="Owner Group" type="I" opts="KF(n:1 => Group.id)"/>
	</table>
	<table name="CRolePerm" opts="S" base="after(_Perm)" disp="Common Role Customizable Extension">
		<field name="rol" disp="Owner Role" type="I" opts="KF(n:1 => Role.id)"/>
	</table>
	<table name="CUserExt" opts="Sx" base="after(_Ext)" disp="Common User Customizable Extension">
		<field name="usr" disp="Owner User" type="I" opts="KF(n:1 => User.id)"/>
	</table>
	<table name="CGroupExt" opts="Sx" base="after(_Ext)" disp="Common Group Customizable Extension">
		<field name="grp" disp="Owner Group" type="I" opts="KF(n:1 => Group.id)"/>
	</table>
	<table name="CRoleExt" opts="Sx" base="after(_Ext)" disp="Common Role Customizable Extension">
		<field name="rol" disp="Owner Role" type="I" opts="KF(n:1 => Role.id)"/>
	</table>
	<table name="CUserRole" opts="Sr" disp="Allocate roles to user">
		<field name="usr" disp="Owner User" type="I" opts="KF(n:1 => User.id)"/>
		<field name="rol" disp="Allocated Rolw" type="I" opts="KF(n:1 => Role.id)"/>
	</table>
	<table name="CGroupRole" opts="Sr" disp="Allocate roles to group">
		<field name="grp" disp="Owner Group" type="I" opts="KF(n:1 => Group.id)"/>
		<field name="rol" disp="Allocated Rolw" type="I" opts="KF(n:1 => Role.id)"/>
	</table>
	<table name="CUserGroup" opts="Sr" disp="Allocate groups to user">
		<field name="usr" disp="Owner User" type="I" opts="KF(n:1 => User.id)"/>
		<field name="grp" disp="Allocated Group" type="I" opts="KF(n:1 => Group.id)"/>
		<field name="memrol" disp="Member Role" type="I" opts="F(n:1 => Role.id)" info="Role.t == 'M'"/>
	</table>
	<table name="CUserS1" opts="Sc" disp="User Security Info (Level 1)">
		<field name="usr" disp="Owner User" type="I" opts="KF(1:1 => User.id)"/>
		<field name="pwd1" disp="Master Password" type="C[40]" info="Control-Purpose"/>
		<field name="pwd2" disp="Secondary Password" type="C[40]" info="Transaction-Purpose, default set to pwd1.
do reset pwd2 by enter pwd1"/>
		<field name="pwd" disp="General Password" type="C[40]" info="General-Purpose, default set to pwd2.
do reset pwd by enter pwd2/pwd1"/>
		<field name="pp1" disp="Plain text of pwd1" type="C[,30]" opts="N"/>
		<field name="pp2" disp="Plain text of pwd2" type="C[,30]" opts="N"/>
		<field name="pp" disp="Plain text of pwd" type="C[,30]" opts="N"/>
		<field name="mail1" disp="Master E-mail" type="C[,80]" info="Control-Purpose
Receive resetted pwd1, pwd2, pwd"/>
		<field name="mail2" disp="Secondary E-mail" type="C[,80]" info="Transaction-Purpose, default set to mail1
Receive resetted pwd2, pwd"/>
		<field name="mail" disp="General E-mail" type="C[,80]" info="General-Purpose, default set to mail2
Receive resetted pwd"/>
		<field name="act1" disp="mail1 is activated" type="I" opts="D(0)"/>
		<field name="act2" disp="mail2 is activated" type="I" opts="D(0)"/>
		<field name="act" disp="mail is activated" type="I" opts="D(0)"/>
		<field name="axt1" disp="mail1 Activation Expiration Time" type="Ts" opts="N" info="set act1 to 0 after axt1 timeout"/>
		<field name="axt2" disp="mail2 Activation Expiration Time" type="Ts" opts="N" info="set act2 to 0 after axt2 timeout"/>
		<field name="axt" disp="mail Activation Expiration Time" type="Ts" opts="N" info="set act to 0 after axt timeout"/>
		<field name="prot_q" disp="Protect Question" type="C[,100]" opts="N"/>
		<field name="prot_a" disp="Protect Answer" type="C[,30]" opts="N"/>
		<field name="keyt" disp="Key Type" type="C[,10]" opts="N" info="SSH, SSH2, X.509, etc."/>
		<field name="prvk" disp="Private Key" type="C[]" opts="N" info="Not used, yet."/>
		<field name="pubk" disp="Public Key" type="C[]" opts="N" info="Not used, yet."/>
	</table>
	<!--User Commons-->
	<table name="CContact" disp="Contact Info">
		<field name="id" disp="id/ctt" type="I" opts="KDi"/>
		<field name="addr" disp="Address" type="C[,200]" opts="N"/>
		<field name="phone" disp="Phone Number" type="C[,30]" opts="N"/>
	</table>
	<table name="CUserContact" opts="Sr" disp="Allocate contacts to user">
		<field name="usr" disp="Owner User" type="I" opts="KF(n:1 => User.id)"/>
		<field name="ctt" disp="Contact" type="I" opts="KF(1:1 => Contact.id)"/>
		<field name="pref" disp="Preference" type="I" opts="D(100)"/>
		<field name="usage" disp="Usage Info" type="C[,30]" opts="N"/>
	</table>
</modpdb>
