=== lenik/jazz/xml/models/p/pdb/pdb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:pdb="http://xml.bodz.net/p/pdb" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xml.bodz.net/p/pdb" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="pdb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="import" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="href" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>href to parent pdb.xml</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="type" type="xs:string">
							<xs:annotation>
								<xs:documentation>reserved</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="pdb:table"/>
					<xs:element ref="pdb:view"/>
				</xs:choice>
			</xs:sequence>
			<xs:attributeGroup ref="pdb:objectAttributes"/>
			<xs:attribute name="qname" type="xs:string">
				<xs:annotation>
					<xs:documentation>qualified package name </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="cat" type="xs:string">
				<xs:annotation>
					<xs:documentation>category</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
		<xs:unique name="u_table_view">
			<xs:selector xpath="pdb:table | pdb:view"/>
			<xs:field xpath="@name"/>
		</xs:unique>
	</xs:element>
	<xs:element name="table">
		<xs:annotation>
			<xs:documentation>REQ: @name

opts: 
    c=abstract
    D=cache/dict
    Dr=redundant (info-dict)
    Ro=read-only table
    S=subtable-deriviation
        Sm=more fields (1:1)
        Sp=properties (1:n:n)
        Sd=details (1:n)
    T=transient table
</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="field" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>REQ: @name

opts: 
    N=nullable
    T(field, ?)=timestamp
    V(field, ?)=version
    S?=special mode
        Sd=cache/display-name
    D(value)=default value
    Dx(sql-exp)=default exp
    Di(gen-method) = identity


and also index opts. </xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attributeGroup ref="pdb:objectAttributes"/>
						<xs:attribute name="type" type="xs:string">
							<xs:annotation>
								<xs:documentation>data type
default C[,32]

b = boolean
B = bit
C[min,max] = 
    char/varchar/text
U[min,max] = 
    nchar/nvarchar/ntext
Y[min,max] = binary
T? = datetime
    Td=date
    Tt=time
    Ts=timestamp
I?=system int
    I1, I2, I4, I8
F?=system float
    F4, F8
N[prec,scale] = numeric/decimal
Z? = N[?,0]
X=XML
O=object</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="index" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>opts: 
    [KFIU]〈id〉(params,  n:m X remote)
    K=primary key
    F=foreign key
    I=index
    U=unique
    
    X: -> normal ref-integrity
        --> no ref-integrity
        => set-null
        >> cascade</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>when index-field is specified both in @opts and this elements, the result is unknown. </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="local" type="xs:string" use="required"/>
									<xs:attribute name="remote" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attributeGroup ref="pdb:objectAttributes"/>
						<xs:attribute name="ref" type="xs:string">
							<xs:annotation>
								<xs:documentation>referenced table (remote table) </xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="check" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sql" type="xs:string"/>
						</xs:sequence>
						<xs:attributeGroup ref="pdb:objectAttributes"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="trigger" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sql" type="xs:string"/>
						</xs:sequence>
						<xs:attributeGroup ref="pdb:objectAttributes"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="pdb:instance" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attributeGroup ref="pdb:objectAttributes"/>
			<xs:attribute name="base" type="xs:string">
				<xs:annotation>
					<xs:documentation>extends the specified table, 

no duplicated fields is allowed.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
		<xs:unique name="u_field">
			<xs:selector xpath="field"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="u_index">
			<xs:selector xpath="index"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="u_check">
			<xs:selector xpath="check"/>
			<xs:field xpath="@name"/>
		</xs:unique>
		<xs:unique name="u_trigger">
			<xs:selector xpath="trigger"/>
			<xs:field xpath="@name"/>
		</xs:unique>
	</xs:element>
	<xs:element name="view">
		<xs:annotation>
			<xs:documentation>REQ: @name

opts: 
    D=cache/dict</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="from" type="pdb:fromType" maxOccurs="unbounded"/>
				<xs:element name="field" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>sql expr returns the field value, or (alias.)* to select all fields. </xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="name" type="xs:string">
									<xs:annotation>
										<xs:documentation>default inferred from expr</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="label" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="filter" type="xs:string" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>sql expr used to filter. 
multiple filters are AND-ed. </xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="groupBy">
					<xs:complexType>
						<xs:attribute name="fields" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>comma-separated field exprs</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="having" type="xs:string">
							<xs:annotation>
								<xs:documentation>sql expr to filter the group</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="sort">
					<xs:annotation>
						<xs:documentation>sql expr used to sort</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="order">
									<xs:annotation>
										<xs:documentation>default ascending</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="ascending"/>
											<xs:enumeration value="descending"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="pdb:objectAttributes"/>
			<xs:attribute name="distinct" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>remove duplicated rows</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="fromType">
		<xs:choice>
			<xs:element name="ref">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string">
						<xs:annotation>
							<xs:documentation>referenced table/view name</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element ref="pdb:view"/>
			<xs:element name="join">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="left" type="pdb:fromType"/>
						<xs:element name="right" type="pdb:fromType"/>
					</xs:sequence>
					<xs:attribute name="mode">
						<xs:annotation>
							<xs:documentation>default is left-join</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="left"/>
								<xs:enumeration value="right"/>
								<xs:enumeration value="natural"/>
								<xs:enumeration value="full"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="alias" type="xs:string">
			<xs:annotation>
				<xs:documentation>alias used in following expr</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="instance">
		<xs:complexType>
			<xs:sequence>
				<xs:any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>field data</xs:documentation>
					</xs:annotation>
				</xs:any>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>instance variable name</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="label" type="xs:string" use="optional"/>
			<xs:attribute name="opts" type="xs:string" use="optional"/>
			<xs:attribute name="tags" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>category for organization purpose.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="doc" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>short help-info</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="objectAttributes">
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>object name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="label" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>display string</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="opts" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>options, in components' local-syntax

Common Options: 
    c=comment-out
    </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="tags" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>category for organization purpose.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="doc" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>short help-info</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
</xs:schema>

=== lenik/jazz/xml/models/p/pdb/samples/forum.xml
<?xml version="1.0" encoding="UTF-8"?>
<pdb xmlns="http://xml.bodz.net/p/pdb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.bodz.net/p/pdb
http://xml.bodz.net/p/pdb/pdb.xsd" package="com.AppName.appdb" name="AppNameForum" label="应用论坛数据库" prefix="Forum">
	<import href="http://xml.bodz.net/p/pdb/samples/accounts.xml"/>
	<table name="Zone" label="论区" ts="both" opts="" doc="讨论区是相关讨论主题的逻辑划分。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="name" label="名称" type="C[, 30]" doc="用于外部引用的名称"/>
		<field name="label" label="标签" type="C[, 30]" doc="显示在讨论区旁边的简短名称。"/>
		<field name="doc" label="描述" type="C[, 200]"/>
		<field name="readOnly" label="只读" type="b" opts="D(0)" doc="不允许回复。"/>
		<field name="audit" label="审核" type="B(THREAD, POST)" doc="需要对发起话题（THREAD）或回复
（POST）进行审核。"/>
	</table>
	<table name="Thread" label="线索" ts="both" opts="Sd(Zone)" doc="讨论主题。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="views" label="阅读数" type="I4" opts="D(0)"/>
		<field name="posts" label="回帖数" type="I4" opts="D(0)"/>
		<field name="iconText" label="文字图标" type="C[, 10]" opts="N" doc="（冗余）"/>
		<field name="subject" label="标题" type="C[, 120]" opts="N" doc="（冗余）"/>
		<field name="lastPostBy" label="最后回复人" type="C[, 10]" opts="N" doc="（冗余）"/>
	</table>
	<table name="Post" label="帖子" ts="both" opts="Sd(Thread)" doc="对某个话题的具体发起或回复的内容
。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="thread" label="所属线索" type="Id" opts="NF(→ Thread)" doc="所属的主题线索。"/>
		<field name="reply" label="回复帖子" type="-" opts="NF(→ Post)" doc="回复的原帖，若为NULL则是发起贴。"/>
		<field name="from" label="发帖者" type="Id" opts="NF(→ User)" doc="帖子的发起人。"/>
		<field name="opts" label="选项" type="C[, 30]" opts="N"/>
		<field name="iconText" label="文字图标" type="C[, 10]" opts="N" doc="文字图标，可能通过字典映射成图形
图标。"/>
		<field name="subject" label="标题" type="C[, 120]" opts="N" doc="帖子的标题，如果是NULL，则和线索
的标题相同。"/>
		<field name="body" label="内容" type="C[,]" doc="帖子的内容。"/>
	</table>
	<table name="ThreadRef" label="线索引用" ts="both" opts="Sd(Thread)" doc="线索的外部引用记录。">
		<field name="system" label="引用系统" type="C[, 30]" opts="U«referer»" doc="被引用的系统指称。"/>
		<field name="sid" label="按索引" type="Id" opts="U«referer»N" doc="系统内的索引。"/>
		<field name="path" label="按地址" type="C[, 200]" opts="N" doc="系统内的路径。"/>
	</table>
	<table name="Attachment" label="附件" ts="both" doc="媒体文件或程序数据。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="name" label="文件名" type="C[, 100]" doc="下载的可更改文件名。"/>
		<field name="_name" label="原始名称" type="C[, 100]" doc="上传时的原文件名。"/>
		<field name="location" label="存储位置" type="C[, 200]" opts="I" doc="一般是服务器所在磁盘路径，也可能
是URL。"/>
		<field name="sha1" label="散列" type="Y20" opts="NI" doc="文件的SHA-1散列值。如果为空则不
作检验。"/>
		<field name="doc" label="描述" type="C[, 200]"/>
		<field name="mimeType" label="媒体类型" type="C[, 40]" opts="I"/>
		<field name="tags" label="标签" type="C[, 100]" opts="I" doc="空格分隔的分类名。"/>
		<field name="credit" label="点数" type="I4" opts="D(0)" doc="可能需要消耗的点数。"/>
		<field name="downloads" label="下载次数" type="I4" opts="I"/>
	</table>
	<table name="PostAttachment" label="帖子附件" opts="Sd(Post)" doc="帖子相关的附件。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="post" label="帖子" type="Id" opts="F(» Post)"/>
		<field name="attachment" label="附件" type="Id" opts="F(» Attachment)"/>
	</table>
	<table name="ZoneListener" label="论区订阅" ts="both" opts="Sd(Zone)" doc="论区更新时需要通知的订阅者。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="zone" label="论区" type="Id" opts="F(» Zone)"/>
		<field name="group" label="订阅用户组" type="Id" opts="NF(» Group)"/>
		<field name="user" label="订阅用户" type="Id" opts="NF(» User)"/>
	</table>
	<table name="ThreadListener" label="线索订阅" ts="both" opts="Sd(Thread)" doc="线索更新时需要通知的订阅者。">
		<field name="id" type="Id" opts="KDi"/>
		<field name="thread" label="线索" type="Id" opts="F(» Thread)"/>
		<field name="group" label="订阅用户组" type="Id" opts="NF(» Group)"/>
		<field name="user" label="订阅用户" type="Id" opts="NF(» User)"/>
	</table>
</pdb>
