=== lenik/jazz/xml/models/n/nfs/task.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 rel. 3 sp1 (http://www.altova.com) by what (ever) -->
<xs:schema xmlns:nt="http://www.bodz.net/xml/current/nfs/task" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsf="http://www.bodz.net/xml/current/xsf" targetNamespace="http://www.bodz.net/xml/current/nfs/task" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://xml.bodz.net/xml/current/xsf" schemaLocation="http://www.bodz.net/xml/current/xsf/base.xsd"/>
	<xs:element name="tasks">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="xsf:structure-composition">
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element ref="nt:task"/>
						<xs:element ref="nt:string"/>
					</xs:choice>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="uri" type="xs:anyURI"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="task">
		<xs:sequence>
			<xs:element name="icon" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>url to icon image</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="keywords" type="xs:string" minOccurs="0">
				<xs:annotation>
					<xs:documentation>keywords for build index</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="summary" minOccurs="0">
				<xs:annotation>
					<xs:documentation>display summary</xs:documentation>
				</xs:annotation>
				<xs:complexType mixed="true">
					<xs:complexContent mixed="true">
						<xs:extension base="xsf:base-content"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="technology" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>technologies used</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:choice>
						<xs:group ref="nt:out-link-group"/>
					</xs:choice>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:group ref="nt:out-link-group" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element ref="nt:task" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string">
			<xs:annotation>
				<xs:documentation>if task name is specified, then the task is defined. </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="ref" type="xs:string">
			<xs:annotation>
				<xs:documentation>if task ref is specified, then the task is a reference to an existing defined task. </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="class" type="xs:string">
			<xs:annotation>
				<xs:documentation>primary-classification</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="title" type="xs:string">
			<xs:annotation>
				<xs:documentation>task display title</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status">
			<xs:annotation>
				<xs:documentation>task status, default open</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="open"/>
					<xs:enumeration value="closed"/>
					<xs:enumeration value="planning"/>
					<xs:enumeration value="development"/>
					<xs:enumeration value="released"/>
					<xs:enumeration value="alpha-test"/>
					<xs:enumeration value="beta-test"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="assoc-class" type="xs:string">
			<xs:annotation>
				<xs:documentation>[NOT USED]</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="facet" type="xs:string">
			<xs:annotation>
				<xs:documentation>facet name of specific sub-task group. </xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mode">
			<xs:annotation>
				<xs:documentation>relation mode, default module. </xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="module"/>
					<xs:enumeration value="dependant"/>
					<xs:enumeration value="outgrowth"/>
					<xs:enumeration value="test"/>
					<xs:enumeration value="develop-utility"/>
					<xs:enumeration value="implement-utility"/>
					<xs:enumeration value="test-utility"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="task" type="nt:task">
		<xs:annotation>
			<xs:documentation>sub-task is identified by parent-task::sub-task</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="string">
		<xs:complexContent>
			<xs:extension base="nt:task">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="stone" type="nt:task">
						<xs:annotation>
							<xs:documentation>sibling stones are with-in dependant mode. </xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="milestone">
						<xs:annotation>
							<xs:documentation>group mark</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:attribute name="name" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="string" type="nt:string"/>
	<!--========== Components ==========-->
	<xs:group name="out-link-group">
		<xs:choice>
			<xs:element name="nfs-note">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="nt:out-link-base">
							<xs:attribute name="section" type="xs:string"/>
							<xs:attribute name="title" type="xs:string" use="required">
								<xs:annotation>
									<xs:documentation>NFS-Title</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="cvs-module">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="nt:out-link-base">
							<xs:attribute name="root" type="xs:string" use="required"/>
							<xs:attribute name="module" type="xs:string" use="required"/>
							<xs:attribute name="user" type="xs:string">
								<xs:annotation>
									<xs:documentation>default anonymous</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="password" type="xs:string"/>
							<xs:attribute name="identity-file" type="xs:string"/>
							<xs:attribute name="branch" type="xs:string">
								<xs:annotation>
									<xs:documentation>default main</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="link">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="nt:out-link-base">
							<xs:attribute name="href" type="xs:string"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:complexType name="out-link-base">
		<xs:attribute name="info" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:schema>

=== lenik/jazz/xml/schema/nfs/test/task-2005.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Snima Denik (Bytes of Danci.Z) -->
<nt:tasks xmlns:nt="http://www.bodz.net/xml/current/nfs/task" xmlns:xsf="http://www.bodz.net/xml/current/xsf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bodz.net/xml/current/nfs/task
http://www.bodz.net/xml/current/nfs/task.xsd">
	<xsf:group xsf:name="XJL" xsf:info="eXtendable JavaScript Library">
		<nt:string name="XJL" title="eXtendable JavaScript Library">
			<nt:stone ref=""/>
			<nt:stone/>
			<nt:stone/>
			<nt:stone ref="GDML/Yacc"/>
			<nt:stone ref="GDMLDom"/>
			<nt:stone ref="XJM"/>
			<nt:stone ref="BXP"/>
			<nt:stone/>
		</nt:string>
		<nt:task/>
		<nt:task name="XJL"/>
		<nt:task/>
		<nt:task name="ScriptDebugger"/>
		<nt:task name="BAS">
			<nt:task name="BSP"/>
			<nt:task name="BSP-ScriptParser">
				<nt:task name="GDML/Yacc">
					<nt:task name="GDMLDom">
						<nt:task name="XJM"/>
					</nt:task>
				</nt:task>
			</nt:task>
			<nt:task name="BSP-Basic"/>
			<nt:task name="BSP-Patch"/>
		</nt:task>
		<nt:task/>
		<nt:task name="XJM"/>
		<nt:task name="BXP"/>
		<nt:task/>
		<nt:task/>
		<nt:task/>
	</xsf:group>
</nt:tasks>
